# Basic docker-compose.yml running the project as docker container.
# Configuration of needed parameters can be done via ./.env file.
# This file isn't loaded into the image, just used as a source for environment variables.

version: "3.9"
services:
  memes-discord-bot:
    image: memes-discord-bot:latest
    build: .
    container_name: memes-discord-bot
    restart: unless-stopped
networks:
  default:
    name: memes-discord-bot-network
    driver: bridge
