# .env file with all configuration variables needed by the bot.
# It can be loaded in python, or used for environment variables.

bot:
  # Your Discord bot token
  token:
  # Command prefix for your bot
  command_prefix: "!"
  # Max possible filesize, by default on Discord it's 8MB
  max_filesize_bytes: 8000000
  # Max character length for "pasta" command output, longer messages will be split
  # By default Discord allows 2000 characters
  max_text_message_length: 2000
  # Intermediate language used to "deep-fry" messages
  # Messages are being first translated to this language,
  # then either to original or configured by users
  deep_fried_language: kk
sources:
  # YAML file containing all sources for commands
  file: sources.yml
