# .env file with all configuration variables needed by the bot.
# It can be loaded in python, or used for environment variables.

bot:
  # Your Discord bot token.
  token:
  # Command prefix for your bot.
  command_prefix: "!"
  # Max possible filesize, by default on Discord it's 8MB.
  max_filesize_bytes: 8000000
  # Max character length for text messages, longer messages will be split into multiple messages.
  # By default Discord allows 2000 characters.
  max_text_message_length: 2000
  # Intermediate languages used to "deep-fry" messages.
  # Messages are being translated to those languages in sequence,
  # then either to original or configured by users.
  # When overwritting you must provide full list of languages, the full list will be replaced.
  deep_fried_languages:
    - km
    - gu
  # Names and aliases for every command.
  # First element on the list is the main name, subsequent ones are optional aliases.
  # When overwritting in custom "settings.yml" you have to overwrite all names,
  # all names will be replaced.
  commands:
    media:
      - media
    text:
      - text
    set_language:
      - setlanguage
      - lang
      - language
    reset_language:
      - resetlanguage
      - resetlang
    deep_fried_text:
      - deepfriedtext
      - dftext
      - dft
sources:
  # YAML file containing all sources for commands.
  file: sources.yml
