# YAML file with all configuration variables needed by the bot.
# Values from this file can be overwritten by another YAML
# which path is supplied by CUSTOM_SETTINGS_PATH environment variable.
# Second YAML doesn't have to contain all parameters, only the ones to overwrite.

bot:
  # Your Discord bot token.
  token:
  # Max possible filesize, by default on Discord it's 8MB.
  max_filesize_bytes: 8000000
  # Max character length for text messages, longer messages will be split into multiple messages.
  # By default Discord allows 2000 characters.
  max_text_message_length: 2000
  # Intermediate languages used to "deep-fry" messages.
  # Messages are being translated to those languages in sequence,
  # then either to original or configured by users.
  # When overwritting you must provide full list of languages, the full list will be replaced.
  deep_fried_languages:
    - km
    - gu
  # Names, descriptions and other additional configuration for every command and subcommand.
  commands:
    # Group of commands related to sending random media.
    media_group:
      # Name of this group, for command like "/media get" this defines "media" part.
      name: media
      # Commands within "media" group
      commands:
        # "/media get" command.
        get:
          # "/media get" command name, this defines "get" part.
          name: get
          # "/media get" command description which is displayed as command hint.
          description: Get a random media
        # "/media periodic" command group.
        periodic:
          # "/media periodic" command group name, defines "periodic" part.
          name: periodic
          # List of hours in 24h (without padded 0) format when bot won't send periodic media.
          quiet_hours: [0, 1, 2, 3, 4, 5, 6, 7]
          enable:
            name: enable
            description: Enable periodic media
            # Hint related to interval of periodic transmissions.
            autocomplete_hint: How often media should be sent in minutes
          disable:
            name: disable
            description: Disable periodic media
          list:
            name: list
            description: List all periodic channels
    # Group of commands related to sending random text.
    # Parameters are similar as for "media" group and its commands.
    text_group:
      name: text
      commands:
        get:
          name: get
          description: Get a random text message
        deep_fry_text:
          name: deepfried
          description: Get a random deep-fried text
      # "language" subgroup in "text" group.
      language_subgroup:
        name: language
        commands:
          set:
            name: set
            description: Set language for text messages
            # Hint displayed when user inputs language parameter itself.
            autocomplete_hint: Output language for text messages
          reset:
            name: reset
            description: Reset language for text messages

sources:
  # YAML file containing all sources for commands.
  file: sources.yml

db:
  # Path to SQLite DB file storing configured text language per Discord channel.
  path: channel_data.db
  # Table name within SQLite DB used for storing languages.
  languages_table_name: language
  # Table name within SQLite DB used for storing periodic media data.
  periodic_table_name: periodic
