# YAML file containing all media and text sources.
# Source name is used only for logging purposes.

media:
  - url: some-media-source-link
    keys:
      - source-key
  - url: some-other-media-source-link
    keys:
      - other-source-key-1
      - other-source-key-2

text:
  - url: text-source-link
    keys:
      - text-source-key
