# YAML file containing all media and text sources.

media:
  - url: some-media-source-link
    # Media URL for this source will be extracted from JSON retrieved from
    # "some-media-source-link" from key "source-key".
    keys:
      - source-key
  - url: some-other-media-source-link
    # Media URL for this source will be extracted from JSON retrieved from
    # "some-other-media-source-link" from nested keys "other-source-key-1" - "other-source-key-2".
    keys:
      - other-source-key-1
      - other-source-key-2
    # Keys used to extract transmitted file title.
    # This field is optional. If it's not present path from URL is used instead.
    title_keys:
      - title-key

text:
  - url: text-source-link-1
    # Text for this source will be extracted from JSON retrieved from "text-source-link-1" directly.
    # "text-source-link" URL itself should return a string.
    keys: []
    # Optional parameter holding code of language of sourced texts.
    # Defaults to english.
    language: en
  - url: text-source-link-2
    # Text for this source will be extracted from JSON retrieved from "text-source-link-1"
    # from "text-source-key" key.
    keys: [text-source-key]
    # Two headers will be added to requests to "text-source-link-2":
    # {header-name-1: header-value-1, header-name-2: header-value-2}
    headers:
      - name: header-name-1
        value: header-value-1
      - name: header-name-2
        value: header-value-2
