# YAML file containing all media and text sources.
# Source name is used only for logging purposes.

media:
  - url: some-media-source-link
    key: source-key
  - url: some-other-media-source-link
    key: other-source-key

text:
  - url: text-source-link
    key: text-source-key
